### ISSUE TITLE
如何编译成静态库

### ISSUE THREAD

**Issue by qiuzi** [Trojan-Plus-Group/trojan-plus#11]
在GCC 6的系统里无法运行 
其关联的lib和boost
有什么办法直接编译成完整的二进制静态形式

**Comment by yuchting** [comment]
In my opinion, you compiler environment might has some problem about glibc or other something. I haven't more experience about this.

Of course you can use the binary in Azure Pipelines, it was built for CentOS 64bit system.

**Comment by qiuzi** [comment]
我觉得借助微软云定期发布二进制版本 这样更便于推广
