### ISSUE TITLE
请教编译出错是咋回事？

### ISSUE THREAD

**Issue by lsq726** [Trojan-Plus-Group/trojan-plus#20]
之前一直挺顺利的，最近编译的时候出错了，是哪个编译器版本出现问题了么？
Run Build Command:"/usr/bin/make" "cmTC_56bc5/fast"
/usr/bin/make -f CMakeFiles/cmTC_56bc5.dir/build.make CMakeFiles/cmTC_56bc5.dir/build
make[1]: Entering directory '/root/trojan-plus/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_56bc5.dir/CheckSymbolExists.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_56bc5.dir/CheckSymbolExists.c.o   -c /root/trojan-plus/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_56bc5
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_56bc5.dir/link.txt --verbose=1
/usr/bin/cc      CMakeFiles/cmTC_56bc5.dir/CheckSymbolExists.c.o  -o cmTC_56bc5 
CMakeFiles/cmTC_56bc5.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_56bc5.dir/build.make:97: recipe for target 'cmTC_56bc5' failed
make[1]: *** [cmTC_56bc5] Error 1
make[1]: Leaving directory '/root/trojan-plus/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_56bc5/fast' failed
make: *** [cmTC_56bc5/fast] Error 2

File /root/trojan-plus/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

**Comment by yuchting** [comment]
CheckSymbolExists.c is not source file of trojan-plus, please delete the build folder to compile again:
`rm -rf /root/trojan-plus/build`

**Comment by yuchting** [comment]
> CheckSymbolExists.c is not source file of trojan-plus, please delete the build folder to compile again:
> `rm -rf /root/trojan-plus/build`

**Comment by lsq726** [comment]
更换乌班图20.04好了

**Comment by yuchting** [comment]
ok, I am going to close this issue now.
