### ISSUE TITLE
是否考虑兼容CDN

### ISSUE THREAD

**Issue by qiuzi** [Trojan-Plus-Group/trojan-plus#6]
现在很多IP被封 借助CDN能复活服务

**Comment by yuchting** [comment]
I haven't test trojan plus via CDN service, but I've heard original trojan project has already support it, you can test it.

**Comment by qiuzi** [comment]
The original trojan does not support websocket
What is the usage scenario of SNI?

**Comment by h31105** [comment]
trojan-go支持websocket&cdn

**Comment by qiuzi** [comment]
@h31105 go语言体积过大 不适合嵌入式平台

**Comment by yuchting** [comment]
I didn't change the original SNI part of config, you can find some information from :
https://trojan-gfw.github.io/trojan/config

I just reviewed some CDN services tech spec and trojan-go websocket implement way:
https://p4gefau1t.github.io/trojan-go/developer/websocket/

of course trojan-plus now cann't do the same thing.

If I have any time in the future, I will add this feature.
