### ISSUE TITLE
[BUG]服务器部署很麻烦

### ISSUE THREAD

**Issue by qiuzi** [Trojan-Plus-Group/trojan-plus#7]
使用的阿里云 ubuntu 按照wiki没法完成编译 能否提供releases

**Comment by yuchting** [comment]
trojan-plus compiling is hard to someone isn't a developer.

If you want help, please paste the error log/output information here, I will check for you.

**Comment by qiuzi** [comment]
`BRARY=/usr/local/lib/mariadb/libmysqlclient.a -DFORCE_TCP_FASTOPEN=ON -DBoost_USE_STATIC_LIBS=ON ..
CMake Error at /usr/local/lib/cmake/Boost-1.73.0/BoostConfig.cmake:141 (find_package):
  Found package configuration file:

    /usr/local/lib/cmake/boost_program_options-1.73.0/boost_program_options-config.cmake

  but it set boost_program_options_FOUND to FALSE so package
  "boost_program_options" is considered to be NOT FOUND.  Reason given by
  package:

  No suitable build variant has been found.

Call Stack (most recent call first):
  /usr/local/lib/cmake/Boost-1.73.0/BoostConfig.cmake:258 (boost_find_component)
  /usr/share/cmake-3.13/Modules/FindBoost.cmake:264 (find_package)
  CMakeLists.txt:203 (find_package)
`

**Comment by qiuzi** [comment]
Trojan Plus v10.0.1 starts.
[2020-07-20 09:40:48] [INFO] connecting to MySQL server xxx.xxxx.xxx:3306
[2020-07-20 09:40:48] [INFO] connected to MySQL server
[2020-07-20 09:40:48] [FATAL] trojan plus service (server) started at 0.0.0.0:1801
出现的[FATAL]但可以用 问题在哪里？

**Comment by yuchting** [comment]
Please ignore the first Fatal information, it's OK
