### ISSUE TITLE
[BUG]NAT模式下无法处理TPROXY tcp

### ISSUE THREAD

**Issue by qiuzi** [Trojan-Plus-Group/trojan-plus#8]
TPROXY的udp能顺利通过 可是tcp却不行

**Comment by yuchting** [comment]
Trojan plus is same as the original trojan project, its NAT mode of TCP only supports iptables' REDIRECT rather than TPROXY.

But trojan plus new UDP forwarding feature needs TPROXY.

**Comment by qiuzi** [comment]
ss-libev已经支持了tcp TPROXY 能借鉴下吗？

**Comment by yuchting** [comment]
I might research this feature in spare time, thanks for your reminder.

**Comment by yuchting** [comment]
implemented in 
https://github.com/Trojan-Plus-Group/trojan-plus/commit/cf635f752f549a27884203a036074ffb7eb6279e
